### ISSUE TITLE
Running the demonstration results in a TclError

### ISSUE THREAD

**Issue by deflatedfruit** [Saadmairaj/tkmacosx#1]
When I run the command `python3 -m tkmacosx` this exception is raised and no window is displayed
`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/tkmacosx/__main__.py", line 192, in <module>
    sample().mainloop()
  File "/usr/local/lib/python3.7/site-packages/tkmacosx/__main__.py", line 67, in __init__
    self.Om1['menu'].entryconfig(i, foreground=list(C_dict)[i])
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 2933, in entryconfigure
    return self._configure(('entryconfigure', index), cnf, kw)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "aqua"`

**Comment by seasonedgeek** [comment]
I had the same issue as **deflatedfruit** during December 2019. Install Python straight from [python.org](https://www.python.org/downloads/) which includes Tcl-Tk builtin.
